######################################################################
# Automatically generated by qmake (3.0) Tue Mar 6 10:10:01 2018
######################################################################

TEMPLATE = app
TARGET = login_app
INCLUDEPATH += .

# Input
HEADERS += login_dialog.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += login_dialog.cpp main.cpp mainwindow.cpp
RESOURCES += resource.qrc
